/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3135.0) */

#include "ble_lns.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside Location and Navigation packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside Location and Navigation packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_LN_FEATURE_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted LN Feature. */ 
#define MAX_LOCATION_AND_SPEED_CHARACTERISTIC_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Location and Speed Characteristic. */ 
#define MAX_POSITION_QUALITY_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Position Quality. */ 
#define MAX_LN_CONTROL_POINT_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted LN Control Point. */ 
#define MAX_NAVIGATION_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Navigation. */ 

/**@brief Function for encoding LN Feature.
 *
 * @param[in]   p_ln_feature              LN Feature structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t ln_feature_ln_feature_encode(ln_feature_ln_feature_t * p_ln_feature, uint8_t * encoded_buffer)
{
    uint32_t ln_feature;
    ln_feature = ln_feature | (p_ln_feature->instantaneous_speed_supported << 0); 
    ln_feature = ln_feature | (p_ln_feature->total_distance_supported << 1); 
    ln_feature = ln_feature | (p_ln_feature->location_supported << 2); 
    ln_feature = ln_feature | (p_ln_feature->elevation_supported << 3); 
    ln_feature = ln_feature | (p_ln_feature->heading_supported << 4); 
    ln_feature = ln_feature | (p_ln_feature->rolling_time_supported << 5); 
    ln_feature = ln_feature | (p_ln_feature->utc_time_supported << 6); 
    ln_feature = ln_feature | (p_ln_feature->remaining_distance_supported << 7); 
    ln_feature = ln_feature | (p_ln_feature->remaining_vertical_distance_supported << 8); 
    ln_feature = ln_feature | (p_ln_feature->estimated_time_of_arrival_supported << 9); 
    ln_feature = ln_feature | (p_ln_feature->number_of_beacons_in_solution_supported << 10); 
    ln_feature = ln_feature | (p_ln_feature->number_of_beacons_in_view_supported << 11); 
    ln_feature = ln_feature | (p_ln_feature->time_to_first_fix_supported << 12); 
    ln_feature = ln_feature | (p_ln_feature->estimated_horizontal_position_error_supported << 13); 
    ln_feature = ln_feature | (p_ln_feature->estimated_vertical_position_error_supported << 14); 
    ln_feature = ln_feature | (p_ln_feature->horizontal_dilution_of_precision_supported << 15); 
    ln_feature = ln_feature | (p_ln_feature->vertical_dilution_of_precision_supported << 16); 
    ln_feature = ln_feature | (p_ln_feature->location_and_speed_characteristic_content_masking_supported << 17); 
    ln_feature = ln_feature | (p_ln_feature->fix_rate_setting_supported << 18); 
    ln_feature = ln_feature | (p_ln_feature->elevation_setting_supported << 19); 
    ln_feature = ln_feature | (p_ln_feature->position_status_supported << 20); 

    return bds_uint32_encode(&ln_feature, &encoded_buffer[0]); 
}

/**@brief Function for encoding LN Feature.
 *
 * @param[in]   p_ln_feature              LN Feature characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t ln_feature_encode(ble_lns_ln_feature_t * p_ln_feature, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += ln_feature_ln_feature_encode(&p_ln_feature->ln_feature, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for encoding Flags.
 *
 * @param[in]   p_flags              Flags structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t location_and_speed_characteristic_flags_encode(location_and_speed_characteristic_flags_t * p_flags, uint8_t * encoded_buffer)
{
    uint16_t flags;
    flags = flags | (p_flags->instantaneous_speed_present << 0); 
    flags = flags | (p_flags->total_distance_present << 1); 
    flags = flags | (p_flags->location_present << 2); 
    flags = flags | (p_flags->elevation_present << 3); 
    flags = flags | (p_flags->heading_present << 4); 
    flags = flags | (p_flags->rolling_time_present << 5); 
    flags = flags | (p_flags->utc_time_present << 6); 
    flags = flags | (p_flags->position_status << 7); 
    flags = flags | (p_flags->speed_and_distance_format << 9); 
    flags = flags | (p_flags->elevation_source << 10); 
    flags = flags | (p_flags->heading_source << 12); 

    return bds_uint16_encode(&flags, &encoded_buffer[0]); 
}

/**@brief Function for encoding Location and Speed Characteristic.
 *
 * @param[in]   p_location_and_speed_characteristic              Location and Speed Characteristic characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t location_and_speed_characteristic_encode(ble_lns_location_and_speed_characteristic_t * p_location_and_speed_characteristic, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += location_and_speed_characteristic_flags_encode(&p_location_and_speed_characteristic->flags, &encoded_buffer[len]); 
    len += bds_uint16_encode(&p_location_and_speed_characteristic->instantaneous_speed, &encoded_buffer[len]); 
    len += bds_uint24_encode(&p_location_and_speed_characteristic->total_distance, &encoded_buffer[len]); 
    if (C1_required)
    {
        len += bds_int32_encode(&p_location_and_speed_characteristic->location___latitude, &encoded_buffer[len]); 
    } 
    if (C1_required)
    {
        len += bds_int32_encode(&p_location_and_speed_characteristic->location___longitude, &encoded_buffer[len]); 
    } 
    len += bds_uint8_array_encode(&p_location_and_speed_characteristic->elevation, &encoded_buffer[len]); 
    len += bds_uint16_encode(&p_location_and_speed_characteristic->heading, &encoded_buffer[len]); 
    encoded_buffer[len++] = p_location_and_speed_characteristic->rolling_time;
    len += bds_ble_date_time_encode(&p_location_and_speed_characteristic->utc_time, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for encoding Flags.
 *
 * @param[in]   p_flags              Flags structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t position_quality_flags_encode(position_quality_flags_t * p_flags, uint8_t * encoded_buffer)
{
    uint16_t flags;
    flags = flags | (p_flags->number_of_beacons_in_solution_present << 0); 
    flags = flags | (p_flags->number_of_beacons_in_view_present << 1); 
    flags = flags | (p_flags->time_to_first_fix_present << 2); 
    flags = flags | (p_flags->ehpe_present << 3); 
    flags = flags | (p_flags->evpe_present << 4); 
    flags = flags | (p_flags->hdop_present << 5); 
    flags = flags | (p_flags->vdop_present << 6); 
    flags = flags | (p_flags->position_status << 7); 

    return bds_uint16_encode(&flags, &encoded_buffer[0]); 
}

/**@brief Function for encoding Position Quality.
 *
 * @param[in]   p_position_quality              Position Quality characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t position_quality_encode(ble_lns_position_quality_t * p_position_quality, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += position_quality_flags_encode(&p_position_quality->flags, &encoded_buffer[len]); 
    encoded_buffer[len++] = p_position_quality->number_of_beacons_in_solution;
    encoded_buffer[len++] = p_position_quality->number_of_beacons_in_view;
    len += bds_uint16_encode(&p_position_quality->time_to_first_fix, &encoded_buffer[len]); 
    len += bds_uint32_encode(&p_position_quality->ehpe, &encoded_buffer[len]); 
    len += bds_uint32_encode(&p_position_quality->evpe, &encoded_buffer[len]); 
    encoded_buffer[len++] = p_position_quality->hdop;
    encoded_buffer[len++] = p_position_quality->vdop;
    return len;
}

/**@brief Function for encoding Op Codes.
 *
 * @param[in]   p_op_codes              Op Codes structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t ln_control_point_op_codes_encode(ln_control_point_op_codes_t * p_op_codes, uint8_t * encoded_buffer)
{
    uint8_t op_codes;
    op_codes = p_op_codes->op_codes;
    encoded_buffer[0] = op_codes;
    return 1; 
}

/**@brief Function for encoding Response Value.
 *
 * @param[in]   p_response_value              Response Value structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t ln_control_point_response_value_encode(ln_control_point_response_value_t * p_response_value, uint8_t * encoded_buffer)
{
    uint8_t response_value;
    response_value = p_response_value->response_value;
    encoded_buffer[0] = response_value;
    return 1; 
}

/**@brief Function for encoding LN Control Point.
 *
 * @param[in]   p_ln_control_point              LN Control Point characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t ln_control_point_encode(ble_lns_ln_control_point_t * p_ln_control_point, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += ln_control_point_op_codes_encode(&p_ln_control_point->op_codes, &encoded_buffer[len]); 
    len += bds_uint8_array_encode(&p_ln_control_point->parameter_value, &encoded_buffer[len]); 
    if (C1_required)
    {
        encoded_buffer[len++] = p_ln_control_point->request_op_code;
    } 
    if (C1_required)
    {
        len += ln_control_point_response_value_encode(&p_ln_control_point->response_value, &encoded_buffer[len]); 
    } 
    if (C2_required)
    {
        len += bds_uint8_array_encode(&p_ln_control_point->response_parameter, &encoded_buffer[len]); 
    } 
    return len;
}

/**@brief Function for decoding Op Codes.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
 static uint8_t ln_control_point_op_codes_decode(uint8_t data_len, uint8_t * p_data, ln_control_point_op_codes_t * p_write_val)
 {
    uint8_t pos = 0; 
    p_write_val->op_codes = (enum_op_codes_t)p_data[pos++]; 
    return pos;
 }
     
/**@brief Function for decoding Response Value.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
 static uint8_t ln_control_point_response_value_decode(uint8_t data_len, uint8_t * p_data, ln_control_point_response_value_t * p_write_val)
 {
    uint8_t pos = 0; 
    p_write_val->response_value = (enum_response_value_t)p_data[pos++]; 
    return pos;
 }
     
/**@brief Function for decoding LN Control Point.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t ln_control_point_decode(uint8_t data_len, uint8_t * p_data, ble_lns_ln_control_point_t * p_write_val)
{
    uint8_t pos = 0;
    pos += ln_control_point_op_codes_decode((data_len-pos), &p_data[pos], &p_write_val->op_codes); 
    pos += bds_uint8_array_decode((data_len-pos), &p_data[pos], &p_write_val->parameter_value); 
    if (C1_required)
        { 
        p_write_val->request_op_code = p_data[pos++]; 
        } 
    if (C1_required)
        { 
        pos += ln_control_point_response_value_decode((data_len-pos), &p_data[pos], &p_write_val->response_value); 
        } 
    if (C2_required)
        { 
        pos += bds_uint8_array_decode((data_len-pos), &p_data[pos], &p_write_val->response_parameter); 
        } 

    return pos;
} 
/**@brief Function for encoding Flags.
 *
 * @param[in]   p_flags              Flags structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t navigation_flags_encode(navigation_flags_t * p_flags, uint8_t * encoded_buffer)
{
    uint16_t flags;
    flags = flags | (p_flags->remaining_distance_present << 0); 
    flags = flags | (p_flags->remaining_vertical_distance_present << 1); 
    flags = flags | (p_flags->estimated_time_of_arrival_present << 2); 
    flags = flags | (p_flags->position_status << 3); 
    flags = flags | (p_flags->heading_source << 5); 
    flags = flags | (p_flags->navigation_indicator_type << 6); 
    flags = flags | (p_flags->waypoint_reached << 7); 
    flags = flags | (p_flags->destination_reached << 8); 

    return bds_uint16_encode(&flags, &encoded_buffer[0]); 
}

/**@brief Function for encoding Navigation.
 *
 * @param[in]   p_navigation              Navigation characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t navigation_encode(ble_lns_navigation_t * p_navigation, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += navigation_flags_encode(&p_navigation->flags, &encoded_buffer[len]); 
    len += bds_uint16_encode(&p_navigation->bearing, &encoded_buffer[len]); 
    len += bds_uint16_encode(&p_navigation->heading, &encoded_buffer[len]); 
    len += bds_uint24_encode(&p_navigation->remaining_distance, &encoded_buffer[len]); 
    len += bds_uint8_array_encode(&p_navigation->remaining_vertical_distance, &encoded_buffer[len]); 
    len += bds_ble_date_time_encode(&p_navigation->estimated_time_of_arrival, &encoded_buffer[len]); 
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_lns       Location and Navigation Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_lns_t * p_lns, ble_evt_t * p_ble_evt)
{
    p_lns->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_lns       Location and Navigation Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_lns_t * p_lns, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_lns->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_lns       Location and Navigation Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_lns_t * p_lns, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_lns->location_and_speed_characteristic_handles.cccd_handle)
    {
        if(p_lns->evt_handler != NULL)
        {
            ble_lns_evt_t evt;
            evt.evt_type = BLE_LNS_LOCATION_AND_SPEED_CHARACTERISTIC_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_lns->evt_handler(p_lns, &evt);
        }
    } 
    if(p_ble_evt->handle == p_lns->ln_control_point_handles.cccd_handle)
    {
        if(p_lns->evt_handler != NULL)
        {
            ble_lns_evt_t evt;
            evt.evt_type = BLE_LNS_LN_CONTROL_POINT_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_lns->evt_handler(p_lns, &evt);
        }
    } 
    if(p_ble_evt->handle == p_lns->ln_control_point_handles.value_handle)
    {
        if(p_lns->evt_handler != NULL)
        {
            ble_lns_evt_t evt;
            evt.evt_type = BLE_LNS_LN_CONTROL_POINT_EVT_WRITE;
            ln_control_point_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.ln_control_point);
            p_lns->evt_handler(p_lns, &evt);
        }
    }
    if(p_ble_evt->handle == p_lns->navigation_handles.cccd_handle)
    {
        if(p_lns->evt_handler != NULL)
        {
            ble_lns_evt_t evt;
            evt.evt_type = BLE_LNS_NAVIGATION_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_lns->evt_handler(p_lns, &evt);
        }
    } 
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_lns_t * p_lns, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
            if (p_auth_req->request.write.handle == p_lns->ln_control_point_handles.value_handle)
            {
                on_write(p_lns, &p_auth_req->request.write);
            }
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_lns       Location and Navigation Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_lns_on_ble_evt(ble_lns_t * p_lns, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_lns, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_lns, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_lns, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_lns, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the Location and Navigation. */
uint32_t ble_lns_init(ble_lns_t * p_lns, const ble_lns_init_t * p_lns_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_lns->evt_handler = p_lns_init->evt_handler;
    p_lns->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    BLE_UUID_BLE_ASSIGN(ble_uuid, 0x1819);
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_lns->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add LN Feature characteristic
    ble_lns_ln_feature_t ln_feature_initial_value = p_lns_init->ble_lns_ln_feature_initial_value; 

    uint8_t ln_feature_encoded_value[MAX_LN_FEATURE_LEN];
    ble_add_char_params_t add_ln_feature_params;
    memset(&add_ln_feature_params, 0, sizeof(add_ln_feature_params));
    
    add_ln_feature_params.uuid                = 0x2A6A; 
    add_ln_feature_params.max_len             = MAX_LN_FEATURE_LEN;
    add_ln_feature_params.init_len            = ln_feature_encode(&ln_feature_initial_value, ln_feature_encoded_value);
    add_ln_feature_params.p_init_value        = ln_feature_encoded_value; 
    add_ln_feature_params.char_props.read     = 1; 
    add_ln_feature_params.read_access         = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_ln_feature_params.is_var_len          = 1; 

    err_code = characteristic_add(p_lns->service_handle, &add_ln_feature_params, &(p_lns->ln_feature_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Location and Speed Characteristic characteristic
    ble_lns_location_and_speed_characteristic_t location_and_speed_characteristic_initial_value = p_lns_init->ble_lns_location_and_speed_characteristic_initial_value; 

    uint8_t location_and_speed_characteristic_encoded_value[MAX_LOCATION_AND_SPEED_CHARACTERISTIC_LEN];
    ble_add_char_params_t add_location_and_speed_characteristic_params;
    memset(&add_location_and_speed_characteristic_params, 0, sizeof(add_location_and_speed_characteristic_params));
    
    add_location_and_speed_characteristic_params.uuid                = 0x2A67; 
    add_location_and_speed_characteristic_params.max_len             = MAX_LOCATION_AND_SPEED_CHARACTERISTIC_LEN;
    add_location_and_speed_characteristic_params.init_len            = location_and_speed_characteristic_encode(&location_and_speed_characteristic_initial_value, location_and_speed_characteristic_encoded_value);
    add_location_and_speed_characteristic_params.p_init_value        = location_and_speed_characteristic_encoded_value; 
    add_location_and_speed_characteristic_params.char_props.notify   = 1; 
    add_location_and_speed_characteristic_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_location_and_speed_characteristic_params.is_var_len          = 1; 

    err_code = characteristic_add(p_lns->service_handle, &add_location_and_speed_characteristic_params, &(p_lns->location_and_speed_characteristic_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Position Quality characteristic
    ble_lns_position_quality_t position_quality_initial_value = p_lns_init->ble_lns_position_quality_initial_value; 

    uint8_t position_quality_encoded_value[MAX_POSITION_QUALITY_LEN];
    ble_add_char_params_t add_position_quality_params;
    memset(&add_position_quality_params, 0, sizeof(add_position_quality_params));
    
    add_position_quality_params.uuid                = 0x2A69; 
    add_position_quality_params.max_len             = MAX_POSITION_QUALITY_LEN;
    add_position_quality_params.init_len            = position_quality_encode(&position_quality_initial_value, position_quality_encoded_value);
    add_position_quality_params.p_init_value        = position_quality_encoded_value; 
    add_position_quality_params.char_props.read     = 1; 
    add_position_quality_params.read_access         = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_position_quality_params.is_var_len          = 1; 

    err_code = characteristic_add(p_lns->service_handle, &add_position_quality_params, &(p_lns->position_quality_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add LN Control Point characteristic
    ble_lns_ln_control_point_t ln_control_point_initial_value = p_lns_init->ble_lns_ln_control_point_initial_value; 

    uint8_t ln_control_point_encoded_value[MAX_LN_CONTROL_POINT_LEN];
    ble_add_char_params_t add_ln_control_point_params;
    memset(&add_ln_control_point_params, 0, sizeof(add_ln_control_point_params));
    
    add_ln_control_point_params.uuid                = 0x2A6B; 
    add_ln_control_point_params.max_len             = MAX_LN_CONTROL_POINT_LEN;
    add_ln_control_point_params.init_len            = ln_control_point_encode(&ln_control_point_initial_value, ln_control_point_encoded_value);
    add_ln_control_point_params.p_init_value        = ln_control_point_encoded_value; 
    add_ln_control_point_params.char_props.indicate = 1; 
    add_ln_control_point_params.char_props.write    = 1; 
    add_ln_control_point_params.write_access        = SEC_OPEN; 
    add_ln_control_point_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_ln_control_point_params.is_var_len          = 1; 

    err_code = characteristic_add(p_lns->service_handle, &add_ln_control_point_params, &(p_lns->ln_control_point_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Navigation characteristic
    ble_lns_navigation_t navigation_initial_value = p_lns_init->ble_lns_navigation_initial_value; 

    uint8_t navigation_encoded_value[MAX_NAVIGATION_LEN];
    ble_add_char_params_t add_navigation_params;
    memset(&add_navigation_params, 0, sizeof(add_navigation_params));
    
    add_navigation_params.uuid                = 0x2A68; 
    add_navigation_params.max_len             = MAX_NAVIGATION_LEN;
    add_navigation_params.init_len            = navigation_encode(&navigation_initial_value, navigation_encoded_value);
    add_navigation_params.p_init_value        = navigation_encoded_value; 
    add_navigation_params.char_props.notify   = 1; 
    add_navigation_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_navigation_params.is_var_len          = 1; 

    err_code = characteristic_add(p_lns->service_handle, &add_navigation_params, &(p_lns->navigation_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the LN Feature. */
uint32_t ble_lns_ln_feature_set(ble_lns_t * p_lns, ble_lns_ln_feature_t * p_ln_feature)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_LN_FEATURE_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = ln_feature_encode(p_ln_feature, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_lns->conn_handle, p_lns->ln_feature_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the Location and Speed Characteristic. */
uint32_t ble_lns_location_and_speed_characteristic_send(ble_lns_t * p_lns, ble_lns_location_and_speed_characteristic_t * p_location_and_speed_characteristic)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_lns->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_LOCATION_AND_SPEED_CHARACTERISTIC_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = location_and_speed_characteristic_encode(p_location_and_speed_characteristic, encoded_value);
        hvx_params.handle = p_lns->location_and_speed_characteristic_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_lns->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

/**@brief Function for setting the Position Quality. */
uint32_t ble_lns_position_quality_set(ble_lns_t * p_lns, ble_lns_position_quality_t * p_position_quality)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_POSITION_QUALITY_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = position_quality_encode(p_position_quality, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_lns->conn_handle, p_lns->position_quality_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the LN Control Point. */
uint32_t ble_lns_ln_control_point_send(ble_lns_t * p_lns, ble_lns_ln_control_point_t * p_ln_control_point)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_lns->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_LN_CONTROL_POINT_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = ln_control_point_encode(p_ln_control_point, encoded_value);
        hvx_params.handle = p_lns->ln_control_point_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_INDICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_lns->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

/**@brief Function for sending the Navigation. */
uint32_t ble_lns_navigation_send(ble_lns_t * p_lns, ble_lns_navigation_t * p_navigation)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_lns->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_NAVIGATION_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = navigation_encode(p_navigation, encoded_value);
        hvx_params.handle = p_lns->navigation_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_lns->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

