/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3135.0) */

#include "service_if.h"
#include <stdint.h>
#include "app_trace.h" 
#include "ble_lns.h" 

static ble_lns_t    m_lns; 

uint8_t m_lns_location_and_speed_characteristic_initial_value_elevation_arr[1]; 
uint8_t m_lns_ln_control_point_initial_value_parameter_value_arr[1]; 
uint8_t m_lns_ln_control_point_initial_value_response_parameter_arr[1]; 
uint8_t m_lns_navigation_initial_value_remaining_vertical_distance_arr[1]; 


/**@brief Function for handling the Location and Navigation events.
 *
 * @details This function will be called for all Location and Navigation events which are passed to
 *          the application.
 *
 * @param[in]   p_location_and_navigation   Location and Navigation structure.
 * @param[in]   p_evt   Event received from the Location and Navigation.
 */
static void on_lns_evt(ble_lns_t * p_lns, ble_lns_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_LNS_LOCATION_AND_SPEED_CHARACTERISTIC_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: LNS_LOCATION_AND_SPEED_CHARACTERISTIC evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_LNS_LOCATION_AND_SPEED_CHARACTERISTIC_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: LNS_LOCATION_AND_SPEED_CHARACTERISTIC evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_LNS_LOCATION_AND_SPEED_CHARACTERISTIC_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: LNS_LOCATION_AND_SPEED_CHARACTERISTIC evt CCCD_WRITE. \r\n");
            break; 
        case BLE_LNS_LN_CONTROL_POINT_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: LNS_LN_CONTROL_POINT evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_LNS_LN_CONTROL_POINT_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: LNS_LN_CONTROL_POINT evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_LNS_LN_CONTROL_POINT_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: LNS_LN_CONTROL_POINT evt CCCD_WRITE. \r\n");
            break; 
        case BLE_LNS_LN_CONTROL_POINT_EVT_WRITE:
            app_trace_log("[Bluetooth_IF]: LNS_LN_CONTROL_POINT evt WRITE. \r\n");
            break; 
        case BLE_LNS_NAVIGATION_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: LNS_NAVIGATION evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_LNS_NAVIGATION_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: LNS_NAVIGATION evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_LNS_NAVIGATION_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: LNS_NAVIGATION evt CCCD_WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
    uint32_t    err_code; 
    ble_lns_init_t    lns_init; 
    

    // Initialize Location and Navigation.
    memset(&lns_init, 0, sizeof(lns_init));

    lns_init.evt_handler = on_lns_evt; 
    memset(&lns_init.ble_lns_location_and_speed_characteristic_initial_value.instantaneous_speed,
           0x00,
           sizeof(lns_init.ble_lns_location_and_speed_characteristic_initial_value.instantaneous_speed));
    memset(&lns_init.ble_lns_location_and_speed_characteristic_initial_value.total_distance,
           0x00,
           sizeof(lns_init.ble_lns_location_and_speed_characteristic_initial_value.total_distance));
    memset(&lns_init.ble_lns_location_and_speed_characteristic_initial_value.location___latitude,
           0x00,
           sizeof(lns_init.ble_lns_location_and_speed_characteristic_initial_value.location___latitude));
    memset(&lns_init.ble_lns_location_and_speed_characteristic_initial_value.location___longitude,
           0x00,
           sizeof(lns_init.ble_lns_location_and_speed_characteristic_initial_value.location___longitude));
    lns_init.ble_lns_location_and_speed_characteristic_initial_value.elevation.size = 1;
    lns_init.ble_lns_location_and_speed_characteristic_initial_value.elevation.p_data = m_lns_location_and_speed_characteristic_initial_value_elevation_arr; 
    memset(&lns_init.ble_lns_location_and_speed_characteristic_initial_value.heading,
           0x00,
           sizeof(lns_init.ble_lns_location_and_speed_characteristic_initial_value.heading));
    memset(&lns_init.ble_lns_location_and_speed_characteristic_initial_value.rolling_time,
           0x00,
           sizeof(lns_init.ble_lns_location_and_speed_characteristic_initial_value.rolling_time));
    memset(&lns_init.ble_lns_location_and_speed_characteristic_initial_value.utc_time,
           0x00,
           sizeof(lns_init.ble_lns_location_and_speed_characteristic_initial_value.utc_time));
    memset(&lns_init.ble_lns_position_quality_initial_value.number_of_beacons_in_solution,
           0x00,
           sizeof(lns_init.ble_lns_position_quality_initial_value.number_of_beacons_in_solution));
    memset(&lns_init.ble_lns_position_quality_initial_value.number_of_beacons_in_view,
           0x00,
           sizeof(lns_init.ble_lns_position_quality_initial_value.number_of_beacons_in_view));
    memset(&lns_init.ble_lns_position_quality_initial_value.time_to_first_fix,
           0x00,
           sizeof(lns_init.ble_lns_position_quality_initial_value.time_to_first_fix));
    memset(&lns_init.ble_lns_position_quality_initial_value.ehpe,
           0x00,
           sizeof(lns_init.ble_lns_position_quality_initial_value.ehpe));
    memset(&lns_init.ble_lns_position_quality_initial_value.evpe,
           0x00,
           sizeof(lns_init.ble_lns_position_quality_initial_value.evpe));
    memset(&lns_init.ble_lns_position_quality_initial_value.hdop,
           0x00,
           sizeof(lns_init.ble_lns_position_quality_initial_value.hdop));
    memset(&lns_init.ble_lns_position_quality_initial_value.vdop,
           0x00,
           sizeof(lns_init.ble_lns_position_quality_initial_value.vdop));
    lns_init.ble_lns_ln_control_point_initial_value.op_codes.op_codes = OP_CODES_SET_CUMULATIVE_VALUE; 
    lns_init.ble_lns_ln_control_point_initial_value.parameter_value.size = 1;
    lns_init.ble_lns_ln_control_point_initial_value.parameter_value.p_data = m_lns_ln_control_point_initial_value_parameter_value_arr; 
    memset(&lns_init.ble_lns_ln_control_point_initial_value.request_op_code,
           0x00,
           sizeof(lns_init.ble_lns_ln_control_point_initial_value.request_op_code));
    lns_init.ble_lns_ln_control_point_initial_value.response_value.response_value = RESPONSE_VALUE_SUCCESS; 
    lns_init.ble_lns_ln_control_point_initial_value.response_parameter.size = 1;
    lns_init.ble_lns_ln_control_point_initial_value.response_parameter.p_data = m_lns_ln_control_point_initial_value_response_parameter_arr; 
    memset(&lns_init.ble_lns_navigation_initial_value.bearing,
           0x00,
           sizeof(lns_init.ble_lns_navigation_initial_value.bearing));
    memset(&lns_init.ble_lns_navigation_initial_value.heading,
           0x00,
           sizeof(lns_init.ble_lns_navigation_initial_value.heading));
    memset(&lns_init.ble_lns_navigation_initial_value.remaining_distance,
           0x00,
           sizeof(lns_init.ble_lns_navigation_initial_value.remaining_distance));
    lns_init.ble_lns_navigation_initial_value.remaining_vertical_distance.size = 1;
    lns_init.ble_lns_navigation_initial_value.remaining_vertical_distance.p_data = m_lns_navigation_initial_value_remaining_vertical_distance_arr; 
    memset(&lns_init.ble_lns_navigation_initial_value.estimated_time_of_arrival,
           0x00,
           sizeof(lns_init.ble_lns_navigation_initial_value.estimated_time_of_arrival));

    err_code = ble_lns_init(&m_lns, &lns_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_lns_on_ble_evt(&m_lns, p_ble_evt); 
}
